# Generated by Django 4.2.7 on 2024-02-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Beverage",
        ),
        migrations.AddField(
            model_name="items",
            name="type",
            field=models.CharField(
                choices=[("food", "Food"), ("beverage", "Beverage")],
                default="food",
                max_length=15,
            ),
        ),
    ]
